# Workflow to build and publish the develop branch

name: Build on develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  develop:
    uses: ./.github/workflows/build-and-pack.yml
    with:
      configuration: "Debug"
      prerelease: "true"
      suffix: "beta"
      publish_target: "nuget.org"
    secrets: inherit
